WithoutIdentity/Models/ManagerViewModels/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WithoutIdentity.Models.ManagerViewModels
{
    public class ChangePasswordViewModel
    {
        [DataType(DataType.Password)]
        [Display(Name = "Confirmar Nova Senha")]
        [Compare(nameof(NewPassword), ErrorMessage = "As senhas devem ser iguais")]
        public string ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Nova Senha")]
        [StringLength(100, ErrorMessage = "O campo {0} deve ter no mínimo {2} e no máximo {1} caracteres,", MinimumLength = 8)]
        public string NewPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Senha Atual")]
        public string OldPassword { get; set; }

        public string StatusMessage { get; set; }
    }
}

WithoutIdentity/Controllers/ManagerController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WithoutIdentity.Models;
using WithoutIdentity.Models.ManagerViewModels;

namespace WithoutIdentity.Controllers
{
    public class ManagerController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public ManagerController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user is null)
            {
                throw new ApplicationException($"Não foi possível carregar o usuário com o Id '{_userManager.GetUserId(User)}'");
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);

            if (!changePasswordResult.Succeeded)
            {
                foreach (var error in changePasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(model);
            }

            await _signInManager.SignInAsync(user, false);

            StatusMessage = "Sua senha foi alterada com sucesso.";

            return RedirectToAction(nameof(ChangePassword));
        }

        [HttpGet]
        public async Task<IActionResult> ChangePassword()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user is null)
            {
                throw new ApplicationException($"Não foi possível carregar o usuário com o Id '{_userManager.GetUserId(User)}'");
            }

            var model = new ChangePasswordViewModel { StatusMessage = StatusMessage };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user is null)
            {
                throw new ApplicationException($"Não foi possível carregar o usuário com o Id '{_userManager.GetUserId(User)}'");
            }

            var model = new IndexViewModel
            {
                Username = user.UserName,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                IsEmailConfirmed = user.EmailConfirmed,
                StatusMessage = StatusMessage
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(IndexViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user is null)
            {
                throw new ApplicationException($"Não foi possível carregar o usuário com o Id '{_userManager.GetUserId(User)}'");
            }

            if (user.Email != model.Email)
            {
                var setEmailResult = await _userManager.SetEmailAsync(user, model.Email);

                if (!setEmailResult.Succeeded)
                {
                    throw new ApplicationException($"Não foi possível atribuir o e-mail ao usuário com o Id '{_userManager.GetUserId(User)}'");
                }
            }

            if (user.PhoneNumber != model.PhoneNumber)
            {
                var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, model.Email);

                if (!setPhoneResult.Succeeded)
                {
                    throw new ApplicationException($"Não foi possível atribuir o telefone ao usuário com o Id '{_userManager.GetUserId(User)}'");
                }
            }

            StatusMessage = "Seu perfil foi atualizado.";

            return RedirectToAction(nameof(Index));
        }
    }
}

WithoutIdentity/Views/Manager/ChangePassword.cshtml
@model ChangePasswordViewModel

@{
  ViewData["Title"] = "Modificar senha";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

@await Html.PartialAsync("_StatusMessage", Model.StatusMessage);

<div class="row">
    <div class="col-md-4">
        <form  method="post">
            <div class="text-danger" asp-validation-summary="All"></div>

            <div class="form-group">
                <label asp-for="OldPassword"></label>
                <input asp-for="OldPassword" class="form-control" disabled/>
            </div>

            <div class="form-group">
                <label asp-for="NewPassword"></label>
                <input asp-for="NewPassword" class="form-control" disabled/>
            </div>

            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" disabled/>
            </div>

            <div class="form-group">
                <button class="btn btn-secondary" type="submit">Salvar</button>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

WithoutIdentity/Views/Manager/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Perfil";
    Layout = "~/Views/Shared/_Layout.cs";
}

<h2>@ViewData["Title"]</h2>

@await Html.PartialAsync("_StatusMessage", Model.StatusMessage);

<div class="row">
    <div class="col-md-4">
        <form  method="post">
            <div class="text-danger" asp-validation-summary="All"></div>

            <div class="form-group">
                <label asp-for="Username"></label>
                <input asp-for="Username" class="form-control" disabled/>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button class="btn btn-secondary" type="submit">Salvar</button>
            </div>
        </form>
    </div>

    <div class="col-md-6">
        <a asp-area="" asp-controller="Manager" asp-action="ChangePassword" title="Alterar Senha">Alterar Senha</a>
    </div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

WithoutIdentity/Views/Manager/_StatusMessage.cshtml
@model string

@if(!string.IsNullOrWhiteSpace(Model))
{
    var statusMessageType = Model.StartsWith("Error") ?  "danger" :  "success";

    <div class="alert alert-@statusMessageType alert-dismissible fade show" role="alert">
        @Model
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
}